baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Olivia Ye'
theme = 'typo'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[taxonomies]
tag = 'tags'

[params]
custom_css = ["assets/_custom.css"]
# Meta description
description = "A Tech Blog"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """
I am a robotics engineer with a strong foundation in mechatronics engineering and a passion for solving complex problems.
I am interested in a range of topics, including sensor integration, robotics software, and electrical engineering.
"""

# Collection to display on home
# homeCollectionTitle = 'Posts'
# homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "~"

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/olivia-w-ye/"

#[[params.social]]
#name = "substack"
#url = "https://medium.com/@user"

[[params.social]]
name = "github"
url = "https://github.com/oliviawxye"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "about"
url = "/about"

[[params.menu]]
name = "resume & portfolio"
url = "/resume_portfolio"

[[params.menu]]
name = "snapshots"
url = "/snapshots"

[[params.menu]]
name = "reads"
url = "/reads"

# [[params.menu]]
# name = "notes"
# url = "/https://notes-82i.pages.dev/"


# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'

[markup.goldmark.renderer]
unsafe = true

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

googlefonts = ["Source Serif 4", "Fira Mono"]
fontbody = 'Source Serif 4'
fontcode = 'Fira Mono'
